[program:cloud_matching_train]
environment=PROC_NAME="%(program_name)s",PYTHONUNBUFFERED="1"
command=/opt/supervisor-scripts/cloud-matching-train.sh
autostart=true
autorestart=unexpected
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
