[program:cloud_matching_adaptive_gate_ustat]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/cloud-matching-adaptive-gate-ustat-train.sh
autostart=false
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
