[program:cloud_matching_tensorboard]
environment=PROC_NAME="%(program_name)s",PYTHONUNBUFFERED="1"
command=/venv/main/bin/tensorboard --logdir /workspace/Cloud-Matching/outputs/l40_softplus_long/tensorboard --host 0.0.0.0 --port 8080
autostart=true
autorestart=unexpected
startsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
